# Generated by Django 4.1.5 on 2023-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='option1',
            new_name='optionA',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='option2',
            new_name='optionB',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='option3',
            new_name='optionC',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='option4',
            new_name='optionD',
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=200),
        ),
    ]
